//! Third-party toolkits (GTK 3/4, libadwaita, Qt …) are **not** restyled: Aqua only gives
//! them traffic-light window controls on the left (GTK: `gtk.css` + `gtk-decoration-layout`,
//! Qt / everything with server-side decorations: Aqua's own title bar) and passes the
//! user's light/dark preference through the standard settings portal.
//!
//! Older versions wrote a whole macOS look for other apps (an `Aqua` GTK 3 theme,
//! libadwaita CSS overrides, a qt6ct palette + stylesheet, Fusion in `kdeglobals`, SF Pro as
//! the UI font). [`remove_legacy_styling`] takes those generated files out again; files a
//! user edited (no Aqua marker) are left alone.
use std::path::Path;

/// Marker in every file written by Aqua.
const OURS: &str = "generated by aqua";

/// Qt platform theme for the session: the portal theme (dark mode and portal file dialogs,
/// no restyling). A value the user set in the environment always wins.
pub fn qt_platform_theme(user: Option<&str>) -> String {
    match user {
        // qt6ct / qt5ct used to be selected by Aqua's old "style apps" option: keep them
        // only when the user has their own qtct configuration
        Some(u @ ("qt6ct" | "qt5ct")) if user_qtct_config(u) => u.to_string(),
        Some("qt6ct" | "qt5ct") => "xdgdesktopportal".into(),
        Some(u) if !u.is_empty() => u.to_string(),
        _ => "xdgdesktopportal".into(),
    }
}

fn is_ours(p: &Path) -> bool {
    std::fs::read_to_string(p).map(|s| s.contains(OURS)).unwrap_or(false)
}

fn user_qtct_config(name: &str) -> bool {
    let Some(conf) = super::theming::config_dir() else { return false };
    let p = conf.join(name).join(format!("{name}.conf"));
    p.exists() && !is_ours(&p)
}

fn remove_if_ours(p: &Path) -> bool {
    if is_ours(p) && std::fs::remove_file(p).is_ok() {
        tracing::info!("removed old Aqua app styling: {}", p.display());
        return true;
    }
    false
}

/// Delete app-wide styling written by older Aqua versions (see the module docs).
pub fn remove_legacy_styling(conf: &Path, data: &Path) {
    for name in ["Aqua", "Aqua-dark"] {
        let dir = data.join("themes").join(name);
        let css = dir.join("gtk-3.0/gtk.css");
        let index = dir.join("index.theme");
        if is_ours(&css) || !css.exists() {
            remove_if_ours(&css);
            remove_if_ours(&index);
            let _ = std::fs::remove_dir(dir.join("gtk-3.0"));
            let _ = std::fs::remove_dir(&dir);
        }
    }
    for dir in ["qt6ct", "qt5ct"] {
        let base = conf.join(dir);
        remove_if_ours(&base.join("colors/Aqua.conf"));
        remove_if_ours(&base.join("qss/aqua.qss"));
        remove_if_ours(&base.join(format!("{dir}.conf")));
    }
    // a kdeglobals written entirely by Aqua (Fusion + recoloured Breeze); user files were
    // only patched and are kept
    remove_if_ours(&conf.join("kdeglobals"));
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn user_qt_theme_wins() {
        assert_eq!(qt_platform_theme(Some("kde")), "kde");
        assert_eq!(qt_platform_theme(None), "xdgdesktopportal");
        assert_eq!(qt_platform_theme(Some("")), "xdgdesktopportal");
    }

    #[test]
    fn legacy_files_removed_user_files_kept() {
        let dir = std::env::temp_dir().join(format!("aqua-legacy-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let (conf, data) = (dir.join("conf"), dir.join("data"));
        let w = |p: &Path, s: &str| {
            std::fs::create_dir_all(p.parent().unwrap()).unwrap();
            std::fs::write(p, s).unwrap();
        };
        w(&data.join("themes/Aqua/gtk-3.0/gtk.css"), "/* generated by aqua */");
        w(&data.join("themes/Aqua/index.theme"), "# generated by aqua");
        w(&conf.join("qt6ct/qt6ct.conf"), "# generated by aqua");
        w(&conf.join("qt5ct/qt5ct.conf"), "[Appearance]\nstyle=Breeze\n");
        w(&conf.join("kdeglobals"), "[General]\nColorScheme=Mine\n");
        remove_legacy_styling(&conf, &data);
        assert!(!data.join("themes/Aqua").exists());
        assert!(!conf.join("qt6ct/qt6ct.conf").exists());
        assert!(conf.join("qt5ct/qt5ct.conf").exists());
        assert!(conf.join("kdeglobals").exists());
        let _ = std::fs::remove_dir_all(&dir);
    }
}
