//! macOS 26 ("Tahoe") look for third-party toolkits.
//!
//! * **GTK 4 / libadwaita** — libadwaita ignores themes, but loads the user stylesheet
//!   `~/.config/gtk-4.0/gtk.css` on top of its own. We override its CSS variables (window,
//!   view, sidebar, accent colours, window radius) for light *and* dark (`@media
//!   (prefers-color-scheme: dark)`, so live appearance switches work) and restyle controls:
//!   glass capsule toolbar buttons, rounded push buttons and fields with an accent focus
//!   ring, capsule search fields, macOS switches, accent-highlighted menus.
//! * **GTK 3** — a real theme, `Aqua` / `Aqua-dark` in `~/.local/share/themes`: GTK's
//!   built-in Adwaita plus the same look written in GTK 3 CSS.
//! * **Qt** — a `qt6ct`/`qt5ct` configuration (Fusion, Aqua palette with the accent, SF
//!   Pro, a stylesheet with rounded controls, portal dialogs). Used when the qt6ct
//!   platform theme is installed (see `qt_platform_theme`).
use std::path::Path;

pub const MARK: &str = "/* generated by aqua */";

/// One appearance's colours (CSS colour strings).
pub struct Palette {
    pub window: &'static str,
    pub view: &'static str,
    pub fg: &'static str,
    pub headerbar: &'static str,
    pub sidebar: &'static str,
    pub card: &'static str,
    pub popover: &'static str,
    /// Push-button face.
    pub button: &'static str,
    pub button_hover: &'static str,
    /// Hairline borders / shadows.
    pub border: &'static str,
    pub glass: &'static str,
    pub glass_hover: &'static str,
    pub glass_rim: &'static str,
    pub field: &'static str,
    pub red: &'static str,
    pub green: &'static str,
    pub yellow: &'static str,
}

pub const LIGHT: Palette = Palette {
    window: "#f3f3f5",
    view: "#ffffff",
    fg: "#1d1d1f",
    headerbar: "#f3f3f5",
    sidebar: "#e9e9ec",
    card: "#ffffff",
    popover: "rgba(248, 248, 250, 0.98)",
    button: "#ffffff",
    button_hover: "#f7f7f9",
    border: "rgba(0, 0, 0, 0.13)",
    glass: "rgba(255, 255, 255, 0.72)",
    glass_hover: "rgba(255, 255, 255, 0.92)",
    glass_rim: "rgba(0, 0, 0, 0.08)",
    field: "#ffffff",
    red: "#ff3b30",
    green: "#28cd41",
    yellow: "#ffcc00",
};

pub const DARK: Palette = Palette {
    window: "#232325",
    view: "#1c1c1e",
    fg: "#f5f5f7",
    headerbar: "#2a2a2c",
    sidebar: "#2c2c2f",
    card: "#2c2c2e",
    popover: "rgba(44, 44, 47, 0.98)",
    button: "#4a4a4d",
    button_hover: "#555558",
    border: "rgba(255, 255, 255, 0.12)",
    glass: "rgba(255, 255, 255, 0.10)",
    glass_hover: "rgba(255, 255, 255, 0.17)",
    glass_rim: "rgba(255, 255, 255, 0.14)",
    field: "rgba(255, 255, 255, 0.07)",
    red: "#ff453a",
    green: "#32d74b",
    yellow: "#ffd60a",
};

/// `#rrggbb` of the accent, scaled by `k` (darker < 1).
pub fn accent_hex(accent: &str, k: f32) -> String {
    let (r, g, b) = aqua_config::accent_rgb(accent);
    let c = |v: f32| (v * k * 255.0).round().clamp(0.0, 255.0) as u8;
    format!("#{:02x}{:02x}{:02x}", c(r), c(g), c(b))
}

fn vars4(p: &Palette) -> String {
    format!(
        "  --window-bg-color: {w}; --window-fg-color: {fg};\n  --view-bg-color: {v}; --view-fg-color: {fg};\n  --headerbar-bg-color: {h}; --headerbar-fg-color: {fg}; --headerbar-backdrop-color: {w};\n  --headerbar-shade-color: {b}; --headerbar-border-color: {b};\n  --sidebar-bg-color: {s}; --sidebar-fg-color: {fg}; --sidebar-backdrop-color: {s}; --sidebar-border-color: {b};\n  --secondary-sidebar-bg-color: {w}; --secondary-sidebar-fg-color: {fg};\n  --card-bg-color: {c}; --card-fg-color: {fg};\n  --popover-bg-color: {p}; --popover-fg-color: {fg};\n  --dialog-bg-color: {w}; --dialog-fg-color: {fg};\n  --destructive-bg-color: {r}; --error-bg-color: {r}; --success-bg-color: {gr}; --warning-bg-color: {y};\n  --aqua-button: {bt}; --aqua-button-hover: {bh}; --aqua-border: {b};\n  --aqua-glass: {g}; --aqua-glass-hover: {gh}; --aqua-glass-rim: {gm}; --aqua-field: {fd};\n",
        w = p.window,
        fg = p.fg,
        v = p.view,
        h = p.headerbar,
        b = p.border,
        s = p.sidebar,
        c = p.card,
        p = p.popover,
        r = p.red,
        gr = p.green,
        y = p.yellow,
        bt = p.button,
        bh = p.button_hover,
        g = p.glass,
        gh = p.glass_hover,
        gm = p.glass_rim,
        fd = p.field,
    )
}

const GTK4_RULES: &str = r#"
/* fonts */
window, .background, popover, tooltip, dialog { font-family: "SF Pro Text", "SF Pro Display", "SF Pro", sans-serif; }

/* windows: larger macOS 26 corners */
window.csd:not(.tiled):not(.tiled-top):not(.tiled-left):not(.tiled-right):not(.tiled-bottom):not(.maximized):not(.fullscreen):not(.solid-csd) { --window-radius: 16px; }

/* toolbar (header bar): unified with the window, items on glass capsules */
headerbar { min-height: 52px; box-shadow: inset 0 -1px color-mix(in srgb, currentColor 8%, transparent); }
headerbar button:not(.titlebutton):not(.suggested-action):not(.destructive-action),
headerbar menubutton > button, headerbar splitbutton > button, headerbar splitbutton > menubutton > button {
  min-height: 30px; min-width: 30px; border-radius: 999px;
  background-color: var(--aqua-glass);
  box-shadow: inset 0 0 0 1px var(--aqua-glass-rim), 0 1px 3px rgba(0, 0, 0, 0.08);
}
headerbar button.image-button:not(.titlebutton) { padding: 0; min-width: 32px; }
headerbar button:not(.titlebutton):hover, headerbar menubutton > button:hover { background-color: var(--aqua-glass-hover); }
headerbar button:not(.titlebutton):active, headerbar button:not(.titlebutton):checked,
headerbar menubutton > button:checked { background-color: color-mix(in srgb, currentColor 16%, var(--aqua-glass)); }
headerbar .linked:not(.vertical) > button:not(:first-child):not(:last-child) { border-radius: 0; }
headerbar .linked:not(.vertical) > button:first-child:not(:last-child) { border-radius: 999px 0 0 999px; }
headerbar .linked:not(.vertical) > button:last-child:not(:first-child) { border-radius: 0 999px 999px 0; }
headerbar button:backdrop { opacity: 0.75; }

/* push buttons */
button:not(.flat):not(.titlebutton):not(.suggested-action):not(.destructive-action):not(.osd):not(.circular):not(.pill):not(.image-button):not(.toggle) {
  border-radius: 8px;
}
.dialog-action-area > button, .response-area > button, button.text-button:not(.flat):not(.suggested-action):not(.destructive-action):not(.osd) {
  background-color: var(--aqua-button);
  box-shadow: inset 0 0 0 1px var(--aqua-border), 0 1px 1.5px rgba(0, 0, 0, 0.10);
}
headerbar button.text-button:not(.suggested-action):not(.destructive-action) { background-color: var(--aqua-glass); }
.dialog-action-area > button:hover, .response-area > button:hover, button.text-button:not(.flat):not(.suggested-action):not(.destructive-action):not(.osd):hover {
  background-color: var(--aqua-button-hover);
}
button.suggested-action, button.destructive-action { border-radius: 8px; box-shadow: 0 1px 2px rgba(0, 0, 0, 0.15); }
button.pill { border-radius: 999px; }

/* text fields: rounded, accent focus ring; search fields are capsules */
entry, spinbutton:not(.vertical), passwordentry {
  border-radius: 8px; background-color: var(--aqua-field);
  box-shadow: inset 0 0 0 1px var(--aqua-border);
  outline-color: color-mix(in srgb, var(--accent-bg-color) 55%, transparent);
}
entry:focus-within, spinbutton:focus-within { box-shadow: inset 0 0 0 1px var(--accent-bg-color); }
searchbar entry, entry.search, headerbar entry { border-radius: 999px; }

/* switches */
switch { border-radius: 999px; padding: 2px; }
switch > slider { border-radius: 999px; min-width: 20px; min-height: 20px; background: #ffffff;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.28), 0 0 0 0.5px rgba(0, 0, 0, 0.06); }
switch:checked { background-color: var(--accent-bg-color); }

/* check boxes and radios */
check { border-radius: 4px; }
radio { border-radius: 999px; }

/* sliders */
scale > trough { min-height: 4px; border-radius: 999px; }
scale.vertical > trough { min-width: 4px; }
scale > trough > slider { min-width: 20px; min-height: 20px; margin: -9px; border-radius: 999px; background: #ffffff;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.3), 0 0 0 0.5px rgba(0, 0, 0, 0.1); }

/* menus and popovers */
popover > contents, popover.menu > contents { border-radius: 12px; padding: 5px; }
popover.menu modelbutton { border-radius: 6px; min-height: 24px; padding: 0 10px; }
popover.menu modelbutton:hover, popover.menu modelbutton:selected { background-color: var(--accent-bg-color); color: #ffffff; }
popover.menu separator { margin: 4px 10px; }
tooltip { border-radius: 8px; }

/* sidebars: rounded grey selection, accent icons */
.navigation-sidebar > row, placessidebar row { border-radius: 8px; min-height: 28px; }
.navigation-sidebar > row:selected, placessidebar row:selected { background-color: color-mix(in srgb, currentColor 12%, transparent); color: inherit; }
.navigation-sidebar > row image, placessidebar row image { color: var(--accent-color); }

/* grouped lists */
list.boxed-list, .card { border-radius: 12px; }
"#;

/// User stylesheet for GTK 4 / libadwaita (appended to the window-controls CSS).
pub fn gtk4_css(accent: &str) -> String {
    let acc = accent_hex(accent, 1.0);
    let acc_text = accent_hex(accent, 0.92);
    let acc_dark_text = accent_hex(accent, 1.15);
    let mut s = String::from("\n/* macOS 26 look (Settings → Appearance → Style other apps) */\n:root {\n");
    s += &format!("  --accent-bg-color: {acc}; --accent-color: {acc_text}; --accent-fg-color: #ffffff;\n");
    s += &vars4(&LIGHT);
    s += "}\n@media (prefers-color-scheme: dark) {\n:root {\n";
    s += &format!("  --accent-color: {acc_dark_text};\n");
    s += &vars4(&DARK);
    s += "}\n}\n";
    s += GTK4_RULES;
    s
}

/// GTK 3 theme stylesheet (`Aqua` / `Aqua-dark`): built-in Adwaita + the Aqua look.
pub fn gtk3_theme_css(dark: bool, accent: &str) -> String {
    let p = if dark { &DARK } else { &LIGHT };
    let acc = accent_hex(accent, 1.0);
    let base = if dark { "gtk-contained-dark.css" } else { "gtk-contained.css" };
    let (pressed, sel_side) = if dark {
        ("rgba(255, 255, 255, 0.18)", "rgba(255, 255, 255, 0.12)")
    } else {
        ("rgba(0, 0, 0, 0.10)", "rgba(0, 0, 0, 0.08)")
    };
    format!(
        r#"{MARK}
/* Aqua (macOS 26 look) for GTK 3 — regenerated by Aqua, edits are overwritten. */
@import url("resource:///org/gtk/libgtk/theme/Adwaita/{base}");

@define-color theme_bg_color {w};
@define-color theme_fg_color {fg};
@define-color theme_base_color {v};
@define-color theme_text_color {fg};
@define-color theme_selected_bg_color {acc};
@define-color theme_selected_fg_color #ffffff;
@define-color accent_bg_color {acc};
@define-color accent_color {acc};

* {{ -gtk-outline-radius: 8px; }}
window, .background {{ font-family: "SF Pro Text", "SF Pro Display", "SF Pro", sans-serif; }}
window.background, .background:not(.titlebar) {{ background-color: {w}; color: {fg}; }}
.view, textview text, iconview, treeview.view {{ background-color: {v}; }}
*:selected, treeview.view:selected, .view:selected {{ background-color: {acc}; color: #ffffff; }}

headerbar, .titlebar:not(headerbar) {{
  min-height: 46px; background: {h}; border-color: {b}; box-shadow: inset 0 -1px {b};
}}
headerbar:backdrop, .titlebar:backdrop {{ background: {w}; }}
headerbar button:not(.titlebutton) {{
  border-radius: 999px; min-height: 26px; min-width: 26px;
  background: {g}; border: 1px solid {gm}; box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08); text-shadow: none; -gtk-icon-shadow: none;
}}
headerbar button:not(.titlebutton):hover {{ background: {gh}; }}
headerbar button:not(.titlebutton):active, headerbar button:not(.titlebutton):checked {{ background: {pressed}; }}
headerbar .linked > button:not(:first-child):not(:last-child) {{ border-radius: 0; }}
headerbar .linked > button:first-child:not(:last-child) {{ border-radius: 999px 0 0 999px; }}
headerbar .linked > button:last-child:not(:first-child) {{ border-radius: 0 999px 999px 0; }}

button:not(.titlebutton):not(.flat) {{
  border-radius: 8px; background: {bt}; border: 1px solid {b};
  box-shadow: 0 1px 1.5px rgba(0, 0, 0, 0.10); text-shadow: none; -gtk-icon-shadow: none;
}}
button:not(.titlebutton):not(.flat):hover {{ background: {bh}; }}
button:not(.titlebutton):not(.flat):active, button:not(.titlebutton):not(.flat):checked {{ background: {pressed}; }}
button.suggested-action {{ background: {acc}; color: #ffffff; border-color: transparent; }}
button.destructive-action {{ background: {red}; color: #ffffff; border-color: transparent; }}
button.flat {{ border-radius: 8px; }}

entry, spinbutton:not(.vertical) {{
  border-radius: 8px; background: {fd}; border: 1px solid {b}; box-shadow: none;
}}
entry:focus, spinbutton:focus {{ border-color: {acc}; box-shadow: 0 0 0 3px alpha({acc}, 0.4); }}
entry.search, searchbar entry, headerbar entry {{ border-radius: 999px; }}

switch {{ border-radius: 999px; background: {pressed}; border: none; }}
switch:checked {{ background: {acc}; }}
switch slider {{ border-radius: 999px; min-width: 22px; min-height: 22px; background: #ffffff; border: none;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.28); }}

check {{ border-radius: 4px; }}
check:checked, radio:checked {{ background: {acc}; color: #ffffff; border-color: {acc}; }}

scale trough {{ min-height: 4px; border-radius: 999px; }}
scale highlight {{ background: {acc}; border-radius: 999px; }}
scale slider {{ min-width: 20px; min-height: 20px; border-radius: 999px; background: #ffffff; border: 1px solid {b};
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.25); }}

menu, .menu, .context-menu {{ background: {pop}; border-radius: 10px; padding: 5px; }}
menuitem {{ border-radius: 6px; min-height: 22px; padding: 2px 10px; }}
menuitem:hover {{ background: {acc}; color: #ffffff; }}
menubar > menuitem:hover {{ background: {pressed}; color: {fg}; }}
popover, popover.background {{ border-radius: 12px; background: {pop}; }}
popover modelbutton {{ border-radius: 6px; }}
popover modelbutton:hover {{ background: {acc}; color: #ffffff; }}
tooltip, tooltip.background {{ border-radius: 8px; }}

.sidebar, placessidebar, stacksidebar {{ background: {s}; }}
placessidebar row, stacksidebar row, .sidebar row {{ border-radius: 8px; margin: 0 6px; }}
placessidebar row:selected, stacksidebar row:selected, .sidebar row:selected {{ background: {sel_side}; color: {fg}; }}
placessidebar row:selected image {{ color: {acc}; }}

notebook > header tab {{ border-radius: 7px; }}
progressbar trough, progressbar progress {{ border-radius: 999px; min-height: 5px; }}
progressbar progress {{ background: {acc}; border: none; }}
scrollbar slider {{ border-radius: 999px; }}
"#,
        w = p.window,
        fg = p.fg,
        v = p.view,
        h = p.headerbar,
        b = p.border,
        g = p.glass,
        gh = p.glass_hover,
        gm = p.glass_rim,
        bt = p.button,
        bh = p.button_hover,
        fd = p.field,
        red = p.red,
        pop = p.popover,
        s = p.sidebar,
    )
}

pub fn gtk3_index_theme(name: &str) -> String {
    format!("# generated by aqua\n[Desktop Entry]\nType=X-GNOME-Metatheme\nName={name}\nComment=macOS 26 look (Aqua)\n\n[X-GNOME-Metatheme]\nGtkTheme={name}\n")
}

/// GTK theme name to set in `settings.ini`: the Aqua theme when app styling is on and the
/// user has not picked another theme (`None`: leave the user's choice alone).
pub fn gtk_theme_choice(current: Option<&str>, dark: bool, style_apps: bool) -> Option<String> {
    let cur = current.unwrap_or("");
    let ours = matches!(cur, "Aqua" | "Aqua-dark");
    let stock = matches!(cur, "" | "Adwaita" | "Adwaita-dark" | "Default");
    if style_apps && (ours || stock) {
        Some(if dark { "Aqua-dark" } else { "Aqua" }.into())
    } else if !style_apps && ours {
        Some(if dark { "Adwaita-dark" } else { "Adwaita" }.into())
    } else {
        None
    }
}

/// Write the GTK 3 theme (both variants) into `data/themes`.
pub fn install_gtk3_theme(data: &Path, accent: &str) {
    for (name, dark) in [("Aqua", false), ("Aqua-dark", true)] {
        let dir = data.join("themes").join(name);
        super::theming::write_if_ours(&dir.join("gtk-3.0/gtk.css"), &gtk3_theme_css(dark, accent), MARK);
        super::theming::write_if_ours(&dir.join("index.theme"), &gtk3_index_theme(name), "generated by aqua");
    }
}

// ---------------------------------------------------------------- Qt (qt6ct / qt5ct)

/// `#aarrggbb` from a `#rrggbb` (or keeps `#aarrggbb`).
fn argb(c: &str, alpha: u8) -> String {
    let h = c.trim_start_matches('#');
    if h.len() == 8 {
        return format!("#{h}");
    }
    format!("#{alpha:02x}{h}")
}

/// qt6ct colour scheme: QPalette roles 0‥21 (WindowText … PlaceholderText, Accent) for the
/// active, disabled and inactive groups.
pub fn qt_color_scheme(dark: bool, accent: &str) -> String {
    let acc = accent_hex(accent, 1.0);
    let (win, base, alt, text, button, light, mid, darkc, shadow, tip, tip_fg, placeholder, link) = if dark {
        (
            "#232325", "#1c1c1e", "#262628", "#f5f5f7", "#3a3a3c", "#4a4a4d", "#2c2c2e", "#141416", "#000000",
            "#3a3a3c", "#f5f5f7", "#8e8e93", "#4da3ff",
        )
    } else {
        (
            "#f3f3f5", "#ffffff", "#f5f5f7", "#1d1d1f", "#ffffff", "#ffffff", "#d1d1d6", "#a1a1a6", "#7f7f7f",
            "#ffffff", "#1d1d1f", "#8e8e93", "#0a66d0",
        )
    };
    let midlight = if dark { "#333335" } else { "#e5e5ea" };
    let roles = |text_c: &str, btn_text: &str, hl: &str| {
        [
            text_c, button, light, midlight, darkc, mid, text_c, "#ffffff", btn_text, base, win, shadow, hl, "#ffffff",
            link, link, alt, "#000000", tip, tip_fg, placeholder, acc.as_str(),
        ]
        .iter()
        .map(|c| argb(c, 0xff))
        .collect::<Vec<_>>()
        .join(", ")
    };
    let dis = if dark { "#6e6e73" } else { "#b0b0b5" };
    let inactive_hl = if dark { "#3a3a3c" } else { "#d4d4d9" };
    format!(
        "# generated by aqua\n[ColorScheme]\nactive_colors={}\ndisabled_colors={}\ninactive_colors={}\n",
        roles(text, text, &acc),
        roles(dis, dis, inactive_hl),
        roles(text, text, &acc)
    )
}

/// Application stylesheet applied by qt6ct/qt5ct on top of Fusion.
pub fn qt_stylesheet(dark: bool, accent: &str) -> String {
    let acc = accent_hex(accent, 1.0);
    let p = if dark { &DARK } else { &LIGHT };
    let (btn, btn_hover, border, pressed, field) = if dark {
        ("#4a4a4d", "#555558", "rgba(255,255,255,0.14)", "#616164", "#2c2c2e")
    } else {
        ("#ffffff", "#f7f7f9", "rgba(0,0,0,0.16)", "#e5e5ea", "#ffffff")
    };
    format!(
        r#"/* generated by aqua — macOS 26 look for Qt (Fusion) */
QPushButton {{ background: {btn}; border: 1px solid {border}; border-radius: 7px; padding: 4px 14px; min-height: 18px; }}
QPushButton:hover {{ background: {btn_hover}; }}
QPushButton:pressed, QPushButton:checked {{ background: {pressed}; }}
QPushButton:default {{ background: {acc}; color: #ffffff; border-color: {acc}; }}
QPushButton:disabled {{ color: palette(placeholder-text); }}
QToolButton {{ border: 1px solid transparent; border-radius: 7px; padding: 3px; }}
QToolButton:hover {{ background: {glass_hover}; border-color: {rim}; }}
QToolButton:pressed, QToolButton:checked {{ background: {pressed}; }}
QToolBar {{ border: none; spacing: 6px; padding: 4px; }}
QLineEdit, QSpinBox, QDoubleSpinBox, QDateTimeEdit, QPlainTextEdit, QTextEdit {{
  background: {field}; border: 1px solid {border}; border-radius: 7px; padding: 3px 6px;
  selection-background-color: {acc}; selection-color: #ffffff; }}
QLineEdit:focus, QSpinBox:focus, QDoubleSpinBox:focus, QPlainTextEdit:focus, QTextEdit:focus {{ border: 2px solid {acc}; padding: 2px 5px; }}
QComboBox {{ background: {btn}; border: 1px solid {border}; border-radius: 7px; padding: 3px 8px; }}
QComboBox:editable {{ background: {field}; }}
QComboBox::drop-down {{ border: none; width: 18px; }}
QMenu {{ background: {pop}; border: 1px solid {border}; padding: 5px; }}
QMenu::item {{ padding: 4px 22px 4px 18px; border-radius: 5px; }}
QMenu::item:selected {{ background: {acc}; color: #ffffff; }}
QMenu::separator {{ height: 1px; background: {border}; margin: 4px 8px; }}
QMenuBar::item:selected {{ background: {pressed}; border-radius: 5px; }}
QToolTip {{ background: {pop}; color: {fg}; border: 1px solid {border}; border-radius: 6px; padding: 4px 8px; }}
QTabBar::tab {{ border-radius: 6px; padding: 4px 12px; margin: 2px; }}
QTabBar::tab:selected {{ background: {btn}; border: 1px solid {border}; }}
QProgressBar {{ border: none; border-radius: 3px; background: {pressed}; max-height: 6px; text-align: center; }}
QProgressBar::chunk {{ background: {acc}; border-radius: 3px; }}
QSlider::groove:horizontal {{ height: 4px; border-radius: 2px; background: {pressed}; }}
QSlider::sub-page:horizontal {{ background: {acc}; border-radius: 2px; }}
QSlider::handle:horizontal {{ background: #ffffff; border: 1px solid {border}; width: 18px; height: 18px; margin: -8px 0; border-radius: 9px; }}
QScrollBar:vertical {{ background: transparent; width: 10px; margin: 2px; }}
QScrollBar:horizontal {{ background: transparent; height: 10px; margin: 2px; }}
QScrollBar::handle {{ background: {dim}; border-radius: 3px; min-height: 24px; min-width: 24px; }}
QScrollBar::add-line, QScrollBar::sub-line, QScrollBar::add-page, QScrollBar::sub-page {{ background: none; border: none; width: 0; height: 0; }}
QGroupBox {{ border: 1px solid {border}; border-radius: 10px; margin-top: 14px; padding: 8px; }}
QGroupBox::title {{ subcontrol-origin: margin; left: 10px; padding: 0 4px; }}
"#,
        glass_hover = p.glass_hover,
        rim = p.glass_rim,
        pop = if dark { "#2c2c2f" } else { "#f8f8fa" },
        fg = p.fg,
        dim = if dark { "rgba(255,255,255,0.35)" } else { "rgba(0,0,0,0.32)" },
    )
}

/// `qt6ct.conf` / `qt5ct.conf` (`qt6`: Qt 6 font string format).
pub fn qtct_conf(colors: &Path, qss: &Path, qt6: bool) -> String {
    let font = |fam: &str| {
        if qt6 {
            format!("\"{fam},10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1\"")
        } else {
            format!("\"{fam},10,-1,5,50,0,0,0,0,0\"")
        }
    };
    format!(
        "# generated by aqua\n[Appearance]\ncolor_scheme_path={}\ncustom_palette=true\nstandard_dialogs=xdgdesktopportal\nstyle=Fusion\n\n[Fonts]\nfixed={}\ngeneral={}\n\n[Interface]\nactivate_item_on_single_click=0\nmenus_have_icons=false\nshow_shortcuts_in_context_menus=true\nstylesheets={}\n",
        colors.display(),
        font("SF Mono"),
        font("SF Pro Display"),
        qss.display()
    )
}

/// Write the qt6ct and qt5ct configuration for the current appearance.
pub fn write_qtct(conf: &Path, dark: bool, accent: &str) {
    for (dir, qt6) in [("qt6ct", true), ("qt5ct", false)] {
        let base = conf.join(dir);
        let colors = base.join("colors/Aqua.conf");
        let qss = base.join("qss/aqua.qss");
        super::theming::write_if_ours(&colors, &qt_color_scheme(dark, accent), "generated by aqua");
        super::theming::write_if_ours(&qss, &qt_stylesheet(dark, accent), "generated by aqua");
        super::theming::write_if_ours(&base.join(format!("{dir}.conf")), &qtct_conf(&colors, &qss, qt6), "generated by aqua");
    }
}

/// Qt platform theme for the session: qt6ct (Aqua palette and stylesheet) when installed
/// and app styling is on, else the portal theme (dark mode, accent, portal dialogs).
/// A value the user set in the environment always wins.
pub fn qt_platform_theme(user: Option<&str>, style_apps: bool, qt6ct_installed: bool) -> String {
    match user {
        Some(u) if !u.is_empty() => u.to_string(),
        _ if style_apps && qt6ct_installed => "qt6ct".into(),
        _ => "xdgdesktopportal".into(),
    }
}

pub fn qt6ct_installed() -> bool {
    ["/usr/lib/qt6/plugins", "/usr/lib64/qt6/plugins", "/usr/lib/x86_64-linux-gnu/qt6/plugins"]
        .iter()
        .any(|d| Path::new(d).join("platformthemes/libqt6ct.so").exists())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn balanced(s: &str) -> bool {
        let mut depth = 0i32;
        for c in s.chars() {
            match c {
                '{' => depth += 1,
                '}' => depth -= 1,
                _ => {}
            }
            if depth < 0 {
                return false;
            }
        }
        depth == 0
    }

    #[test]
    fn gtk4_css_has_both_appearances_and_accent() {
        let css = gtk4_css("orange");
        assert!(balanced(&css));
        assert!(css.contains("@media (prefers-color-scheme: dark)"));
        assert!(css.contains(&format!("--accent-bg-color: {}", accent_hex("orange", 1.0))));
        assert!(css.contains(&format!("--window-bg-color: {}", LIGHT.window)));
        assert!(css.contains(&format!("--window-bg-color: {}", DARK.window)));
        // every custom variable we use is defined
        for v in ["--aqua-glass", "--aqua-glass-rim", "--aqua-glass-hover", "--aqua-button", "--aqua-border", "--aqua-field"] {
            assert!(css.contains(&format!("{v}:")), "{v} undefined");
        }
    }

    #[test]
    fn gtk3_css_is_plain_gtk3() {
        for dark in [false, true] {
            let css = gtk3_theme_css(dark, "blue");
            assert!(balanced(&css));
            assert!(css.starts_with(MARK));
            for modern in ["var(", "color-mix", ":root", "@media"] {
                assert!(!css.contains(modern), "GTK 3 does not understand {modern}");
            }
            assert!(css.contains(if dark { "gtk-contained-dark.css" } else { "gtk-contained.css\"" }));
        }
    }

    #[test]
    fn theme_choice_respects_user_themes() {
        assert_eq!(gtk_theme_choice(None, false, true).as_deref(), Some("Aqua"));
        assert_eq!(gtk_theme_choice(Some("Adwaita"), true, true).as_deref(), Some("Aqua-dark"));
        assert_eq!(gtk_theme_choice(Some("Aqua-dark"), false, true).as_deref(), Some("Aqua"));
        assert_eq!(gtk_theme_choice(Some("Orchis"), true, true), None, "a user theme stays");
        assert_eq!(gtk_theme_choice(Some("Aqua"), true, false).as_deref(), Some("Adwaita-dark"), "turning off reverts");
        assert_eq!(gtk_theme_choice(Some("Adwaita"), true, false), None);
    }

    #[test]
    fn qt_palette_shape() {
        let s = qt_color_scheme(true, "purple");
        for key in ["active_colors=", "disabled_colors=", "inactive_colors="] {
            let line = s.lines().find(|l| l.starts_with(key)).expect(key);
            let cols: Vec<&str> = line[key.len()..].split(", ").collect();
            assert_eq!(cols.len(), 22, "{key}");
            assert!(cols.iter().all(|c| c.len() == 9 && c.starts_with("#ff")), "{cols:?}");
        }
        let acc = accent_hex("purple", 1.0);
        assert!(s.contains(&format!("#ff{}", &acc[1..])));
    }

    #[test]
    fn qt_stylesheet_and_conf() {
        let qss = qt_stylesheet(false, "green");
        assert!(balanced(&qss));
        assert!(qss.contains(&accent_hex("green", 1.0)));
        let conf = qtct_conf(Path::new("/c/Aqua.conf"), Path::new("/c/aqua.qss"), true);
        assert!(conf.contains("color_scheme_path=/c/Aqua.conf"));
        assert!(conf.contains("stylesheets=/c/aqua.qss"));
        assert!(conf.contains("standard_dialogs=xdgdesktopportal"));
        assert!(conf.contains(",400,"), "Qt 6 font weight");
        assert!(qtct_conf(Path::new("/a"), Path::new("/b"), false).contains(",50,"), "Qt 5 font weight");
    }

    #[test]
    fn qt_platform_theme_choice() {
        assert_eq!(qt_platform_theme(Some("kde"), true, true), "kde");
        assert_eq!(qt_platform_theme(None, true, true), "qt6ct");
        assert_eq!(qt_platform_theme(Some(""), true, false), "xdgdesktopportal");
        assert_eq!(qt_platform_theme(None, false, true), "xdgdesktopportal");
    }

    #[test]
    fn files_are_written_and_user_files_kept() {
        let dir = std::env::temp_dir().join(format!("aqua-apptheme-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        install_gtk3_theme(&dir, "blue");
        let light = std::fs::read_to_string(dir.join("themes/Aqua/gtk-3.0/gtk.css")).unwrap();
        assert!(light.contains("gtk-contained.css"));
        assert!(dir.join("themes/Aqua-dark/index.theme").exists());
        write_qtct(&dir, true, "red");
        assert!(std::fs::read_to_string(dir.join("qt6ct/qt6ct.conf")).unwrap().contains("Aqua.conf"));
        // a user's own file is never replaced
        std::fs::write(dir.join("qt5ct/qt5ct.conf"), "[Appearance]\nstyle=kvantum\n").unwrap();
        write_qtct(&dir, false, "red");
        assert_eq!(std::fs::read_to_string(dir.join("qt5ct/qt5ct.conf")).unwrap(), "[Appearance]\nstyle=kvantum\n");
        let _ = std::fs::remove_dir_all(&dir);
    }
}
