//! Client theming: make GTK/Qt apps blend in (traffic-light window controls on the
//! left, SF Pro font, accent). Files are only written when absent or when they
//! were generated by Aqua before (marker comment), so user customisations survive.
use std::path::{Path, PathBuf};

const MARK: &str = "/* generated by aqua */";

const GTK_CSS: &str = r#"/* generated by aqua */
/* Aqua style window controls for GTK3/GTK4/libadwaita.
   The dot is painted with a radial gradient sized `closest-side`, so it stays a 14px
   circle even when a header bar stretches the button vertically (border-radius on the
   button itself turned stretched buttons into pills). */
windowcontrols { border-spacing: 8px; margin: 0 6px; }
windowcontrols > button, headerbar button.titlebutton, .titlebar button.titlebutton {
  min-width: 14px; min-height: 14px; padding: 0; margin: 0 1px;
  border: none; border-radius: 0; box-shadow: none; outline: none;
  background-color: transparent;
  background-repeat: no-repeat; background-position: center; background-size: 14px 14px;
  -gtk-icon-shadow: none; text-shadow: none;
}
windowcontrols > button > image, headerbar button.titlebutton image, .titlebar button.titlebutton image {
  background: none; box-shadow: none; padding: 0; margin: 0;
  opacity: 0; -gtk-icon-size: 8px; color: rgba(0,0,0,0.6);
}
windowcontrols:hover > button > image, headerbar:hover button.titlebutton image { opacity: 1; }
windowcontrols > button.close, headerbar button.titlebutton.close, .titlebar button.titlebutton.close {
  background-image: radial-gradient(circle closest-side, #ff5f57 0%, #ff5f57 88%, #e2463f 92%, transparent 100%); }
windowcontrols > button.minimize, headerbar button.titlebutton.minimize, .titlebar button.titlebutton.minimize {
  background-image: radial-gradient(circle closest-side, #febc2e 0%, #febc2e 88%, #e1a116 92%, transparent 100%); }
windowcontrols > button.maximize, headerbar button.titlebutton.maximize, .titlebar button.titlebutton.maximize {
  background-image: radial-gradient(circle closest-side, #28c840 0%, #28c840 88%, #1aab29 92%, transparent 100%); }
windowcontrols > button:backdrop, headerbar button.titlebutton:backdrop, .titlebar button.titlebutton:backdrop {
  background-image: radial-gradient(circle closest-side, #d0d0d2 0%, #d0d0d2 88%, #bdbdc0 92%, transparent 100%); }
windowcontrols > button:hover, windowcontrols > button:active, headerbar button.titlebutton:hover, headerbar button.titlebutton:active {
  background-color: transparent; box-shadow: none; }
@define-color accent_bg_color #0a84ff;
@define-color accent_color #0a7aff;
window, .background { font-family: "SF Pro Display", "SF Pro", sans-serif; }
"#;

fn write_if_ours(path: &Path, content: &str, marker: &str) {
    if let Ok(old) = std::fs::read_to_string(path) {
        if !old.contains(marker) {
            return;
        }
        if old == content {
            return;
        }
    }
    if let Some(dir) = path.parent() {
        let _ = std::fs::create_dir_all(dir);
    }
    let _ = std::fs::write(path, content);
}

/// Set `key=value` pairs in an INI/keyfile, keeping every other line of a user's file.
fn upsert_ini(path: &Path, sections: &[(&str, Vec<(&str, String)>)]) {
    let old = std::fs::read_to_string(path).unwrap_or_else(|_| "# generated by aqua\n".into());
    let mut lines: Vec<String> = old.lines().map(str::to_string).collect();
    for (sec, kv) in sections {
        let head = format!("[{sec}]");
        let start = match lines.iter().position(|l| l.trim() == head) {
            Some(i) => i,
            None => {
                if lines.last().map(|l| !l.trim().is_empty()).unwrap_or(false) {
                    lines.push(String::new());
                }
                lines.push(head.clone());
                lines.len() - 1
            }
        };
        for (k, v) in kv {
            let end = lines
                .iter()
                .enumerate()
                .skip(start + 1)
                .find(|(_, l)| l.trim_start().starts_with('['))
                .map(|(i, _)| i)
                .unwrap_or(lines.len());
            let line = format!("{k}={v}");
            match (start + 1..end).find(|&i| lines[i].split_once('=').map(|(a, _)| a.trim() == *k).unwrap_or(false)) {
                Some(i) => lines[i] = line,
                None => {
                    let mut at = end;
                    while at > start + 1 && lines[at - 1].trim().is_empty() {
                        at -= 1;
                    }
                    lines.insert(at, line);
                }
            }
        }
    }
    let mut out = lines.join("\n");
    out.push('\n');
    if out != old {
        if let Some(dir) = path.parent() {
            let _ = std::fs::create_dir_all(dir);
        }
        let _ = std::fs::write(path, out);
    }
}

/// Install SF Pro into the user font dir so clients can use it too.
fn install_fonts(font_dir: &Path) {
    let Some(data) = dirs_data() else { return };
    let dst = data.join("fonts/aqua");
    let Ok(rd) = std::fs::read_dir(font_dir) else { return };
    let _ = std::fs::create_dir_all(&dst);
    let mut changed = false;
    for e in rd.flatten() {
        let p = e.path();
        if p.extension().map(|x| x == "otf" || x == "ttf").unwrap_or(false) {
            let t = dst.join(p.file_name().unwrap());
            if !t.exists() && std::fs::copy(&p, &t).is_ok() {
                changed = true;
            }
        }
    }
    if changed {
        let _ = std::process::Command::new("fc-cache").arg("-f").arg(&dst).spawn();
    }
}

fn dirs_data() -> Option<PathBuf> {
    std::env::var_os("XDG_DATA_HOME")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".local/share")))
}

fn dirs_config() -> Option<PathBuf> {
    std::env::var_os("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".config")))
}

const FX_BEGIN: &str = "// >>> aqua (generated, edit outside this block)";
const FX_END: &str = "// <<< aqua";

/// Firefox draws its own Adwaita-like round titlebar buttons since 117
/// (`widget.gtk.non-native-titlebar-buttons.enabled`).
fn firefox_prefs() -> String {
    format!(
        "{FX_BEGIN}\nuser_pref(\"widget.gtk.non-native-titlebar-buttons.enabled\", false);\nuser_pref(\"browser.tabs.inTitlebar\", 1);\nuser_pref(\"widget.use-xdg-desktop-portal.file-picker\", 1);\nuser_pref(\"toolkit.legacyUserProfileCustomizations.stylesheets\", true);\n{FX_END}\n"
    )
}

const CSS_BEGIN: &str = "/* >>> aqua (generated, edit outside this block) */";
const CSS_END: &str = "/* <<< aqua */";

/// Newer Gecko builds (Firefox ≥ 128, Zen, Floorp, LibreWolf) always draw their own
/// round Adwaita-style titlebar buttons and ignore the GTK theme and the pref above, so
/// the traffic lights are painted from userChrome.css (works for native buttons too).
const FX_CHROME_CSS: &str = r#"/* >>> aqua (generated, edit outside this block) */
.titlebar-buttonbox { gap: 8px !important; margin-inline: 10px !important; align-items: center !important; }
.titlebar-buttonbox-container { align-items: center !important; }
.titlebar-button {
  appearance: none !important; padding: 0 !important; margin: 0 !important; min-width: 0 !important; min-height: 0 !important;
  background: none !important; border: none !important; box-shadow: none !important; outline: none !important;
}
.titlebar-button > .toolbarbutton-icon {
  width: 14px !important; height: 14px !important; min-width: 14px !important; min-height: 14px !important; padding: 2px !important;
  border-radius: 50% !important; background-color: #ff5f57 !important; box-shadow: inset 0 0 0 0.5px rgba(0, 0, 0, 0.18) !important;
  -moz-context-properties: fill, fill-opacity, stroke !important; fill: transparent !important; stroke: transparent !important; color: transparent !important;
  opacity: 1 !important; filter: none !important; transition: none !important;
}
.titlebar-close > .toolbarbutton-icon { background-color: #ff5f57 !important; }
.titlebar-min > .toolbarbutton-icon { background-color: #febc2e !important; }
.titlebar-max > .toolbarbutton-icon, .titlebar-restore > .toolbarbutton-icon { background-color: #28c840 !important; }
/* own glyphs (the stock Adwaita ones look wrong), shown while the group is hovered */
.titlebar-button { list-style-image: none !important; }
.titlebar-buttonbox:hover .titlebar-close { list-style-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 10 10'%3E%3Cpath d='M2.75 2.75l4.5 4.5M7.25 2.75l-4.5 4.5' stroke='%23000' stroke-opacity='.55' stroke-width='1.25' stroke-linecap='round'/%3E%3C/svg%3E") !important; }
.titlebar-buttonbox:hover .titlebar-min { list-style-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 10 10'%3E%3Cpath d='M2.3 5h5.4' stroke='%23000' stroke-opacity='.55' stroke-width='1.25' stroke-linecap='round'/%3E%3C/svg%3E") !important; }
.titlebar-buttonbox:hover .titlebar-max { list-style-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 10 10'%3E%3Cpath d='M2.5 7V3.1L6.4 7z M7.5 3v3.9L3.6 3z' fill='%23000' fill-opacity='.55'/%3E%3C/svg%3E") !important; }
.titlebar-buttonbox:hover .titlebar-restore { list-style-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 10 10'%3E%3Cpath d='M4.6 5.4H1.6l3 3z M5.4 4.6h3l-3-3z' fill='%23000' fill-opacity='.55'/%3E%3C/svg%3E") !important; }
.titlebar-button:hover:active > .toolbarbutton-icon { filter: brightness(0.85) !important; }
:root:-moz-window-inactive .titlebar-buttonbox:not(:hover) .titlebar-button > .toolbarbutton-icon { background-color: #d0d0d2 !important; box-shadow: inset 0 0 0 0.5px rgba(0, 0, 0, 0.12) !important; }
@media (prefers-color-scheme: dark) {
  :root:-moz-window-inactive .titlebar-buttonbox:not(:hover) .titlebar-button > .toolbarbutton-icon { background-color: #4b4b4e !important; }
}
/* <<< aqua */
"#;

/// Insert/refresh our marked block in a text file, keeping everything else.
fn upsert_block(path: &Path, begin: &str, end: &str, block: &str) {
    let old = std::fs::read_to_string(path).unwrap_or_default();
    let new = match (old.find(begin), old.find(end)) {
        (Some(a), Some(b)) if b > a => {
            let e = old[b..].find('\n').map(|i| b + i + 1).unwrap_or(old.len());
            format!("{}{}{}", &old[..a], block, &old[e..])
        }
        _ => format!("{old}{}{block}", if old.is_empty() || old.ends_with('\n') { "" } else { "\n" }),
    };
    if new != old {
        if let Some(d) = path.parent() {
            let _ = std::fs::create_dir_all(d);
        }
        let _ = std::fs::write(path, new);
    }
}

/// Profile directories listed in Firefox-family profiles.ini files.
fn mozilla_profiles() -> Vec<PathBuf> {
    let mut out = vec![];
    let Some(home) = std::env::var_os("HOME").map(PathBuf::from) else { return out };
    let conf = dirs_config().unwrap_or_else(|| home.join(".config"));
    let flat = home.join(".var/app");
    let roots = [
        home.join(".mozilla/firefox"),
        conf.join("mozilla/firefox"),
        home.join(".librewolf"),
        home.join(".floorp"),
        home.join(".zen"),
        conf.join("zen"),
        home.join(".waterfox"),
        home.join(".mullvad-browser"),
        flat.join("org.mozilla.firefox/.mozilla/firefox"),
        flat.join("org.mozilla.firefox/config/mozilla/firefox"),
        flat.join("app.zen_browser.zen/.zen"),
        flat.join("io.gitlab.librewolf-community/.librewolf"),
        flat.join("one.ablaze.floorp/.floorp"),
        flat.join("net.waterfox.waterfox/.waterfox"),
    ];
    for root in roots {
        let Ok(ini) = std::fs::read_to_string(root.join("profiles.ini")) else { continue };
        let mut rel = true;
        let mut path: Option<String> = None;
        let flush = |rel: bool, path: &mut Option<String>, out: &mut Vec<PathBuf>| {
            if let Some(p) = path.take() {
                let d = if rel { root.join(&p) } else { PathBuf::from(&p) };
                if d.is_dir() && !out.contains(&d) {
                    out.push(d);
                }
            }
        };
        for line in ini.lines() {
            let l = line.trim();
            if l.starts_with('[') {
                flush(rel, &mut path, &mut out);
                rel = true;
            } else if let Some(v) = l.strip_prefix("Path=") {
                path = Some(v.to_string());
            } else if let Some(v) = l.strip_prefix("IsRelative=") {
                rel = v.trim() != "0";
            }
        }
        flush(rel, &mut path, &mut out);
    }
    out
}

/// Insert/refresh our block in each profile's user.js (the rest of the file is kept).
fn theme_firefox() {
    let block = firefox_prefs();
    for prof in mozilla_profiles() {
        upsert_block(&prof.join("user.js"), FX_BEGIN, FX_END, &block);
        upsert_block(&prof.join("chrome/userChrome.css"), CSS_BEGIN, CSS_END, FX_CHROME_CSS);
    }
}

/// Chromium-family browsers: when the user never chose a frame style, use the system (server-side)
/// title bar so Aqua draws real traffic lights, and follow the GTK theme.
fn theme_chromium() {
    let Some(conf) = dirs_config() else { return };
    let browsers = [
        ("chromium", "chromium"),
        ("google-chrome", "chrome"),
        ("google-chrome-beta", "chrome"),
        ("BraveSoftware/Brave-Browser", "brave"),
        ("vivaldi", "vivaldi-bin"),
        ("microsoft-edge", "msedge"),
        ("yandex-browser", "yandex_browser"),
        ("thorium", "thorium"),
    ];
    let running = running_exes();
    for (dir, exe) in browsers {
        let prefs = conf.join(dir).join("Default/Preferences");
        let Ok(text) = std::fs::read_to_string(&prefs) else { continue };
        if running.iter().any(|r| r == exe || r.starts_with(exe)) {
            continue;
        }
        let Ok(mut v) = serde_json::from_str::<serde_json::Value>(&text) else { continue };
        let Some(root) = v.as_object_mut() else { continue };
        let mut changed = false;
        let browser = root.entry("browser").or_insert_with(|| serde_json::json!({}));
        if let Some(b) = browser.as_object_mut() {
            if !b.contains_key("custom_chrome_frame") {
                b.insert("custom_chrome_frame".into(), serde_json::Value::Bool(false));
                changed = true;
            }
        }
        if changed {
            if let Ok(s) = serde_json::to_string(&v) {
                let _ = std::fs::write(&prefs, s);
                tracing::info!("{dir}: using the system title bar (Aqua traffic lights)");
            }
        }
    }
}

fn running_exes() -> Vec<String> {
    let mut v = vec![];
    if let Ok(rd) = std::fs::read_dir("/proc") {
        for e in rd.flatten() {
            if let Ok(c) = std::fs::read_to_string(e.path().join("comm")) {
                v.push(c.trim().to_string());
            }
        }
    }
    v
}

/// GTK 3 has no built-in "Adwaita-dark" theme name (distributions ship a stub in
/// gnome-themes-extra).
fn ensure_adwaita_dark() {
    let Some(data) = dirs_data() else { return };
    let sys = ["/usr/share/themes/Adwaita-dark/gtk-3.0", "/usr/local/share/themes/Adwaita-dark/gtk-3.0"];
    if sys.iter().any(|d| Path::new(d).is_dir()) {
        return;
    }
    let dir = data.join("themes/Adwaita-dark/gtk-3.0");
    let css =
        "/* generated by aqua */\n@import url(\"resource:///org/gtk/libgtk/theme/Adwaita/gtk-contained-dark.css\");\n";
    write_if_ours(&dir.join("gtk.css"), css, MARK);
    write_if_ours(&data.join("themes/Adwaita-dark/index.theme"), "# generated by aqua\n[Desktop Entry]\nType=X-GNOME-Metatheme\nName=Adwaita-dark\n\n[X-GNOME-Metatheme]\nGtkTheme=Adwaita-dark\n", "generated by aqua");
}

pub fn apply(cfg: &aqua_config::Config) {
    install_fonts(&cfg.font_dir());
    ensure_adwaita_dark();
    *ACCENT.lock().unwrap() = cfg.accent.clone();
    write_appearance(cfg.dark);
    write_qt(cfg.dark, &cfg.accent);
    if cfg.theme_browsers {
        std::thread::spawn(|| {
            theme_firefox();
            theme_chromium();
        });
    }
    unsafe {
        std::env::set_var("XDG_CURRENT_DESKTOP", "Aqua");
        if std::env::var_os("GSETTINGS_BACKEND").is_none() {
            std::env::set_var("GSETTINGS_BACKEND", "keyfile");
        }
        std::env::set_var("XDG_SESSION_TYPE", "wayland");
        std::env::set_var("MOZ_ENABLE_WAYLAND", "1");
        std::env::set_var("QT_QPA_PLATFORM", "wayland;xcb");
        if std::env::var_os("QT_QPA_PLATFORMTHEME").is_none() {
            std::env::set_var("QT_QPA_PLATFORMTHEME", "xdgdesktopportal");
        }
        std::env::set_var("GDK_BACKEND", "wayland,x11");
        std::env::set_var("_JAVA_AWT_WM_NONREPARENTING", "1");
    }
}

/// Accent of the last applied config (Control Center's Dark Mode toggle reuses it).
static ACCENT: std::sync::Mutex<String> = std::sync::Mutex::new(String::new());

/// libadwaita / GNOME accent names for Aqua's accent colours.
fn gnome_accent(a: &str) -> &'static str {
    match a {
        "purple" => "purple",
        "pink" => "pink",
        "red" => "red",
        "orange" => "orange",
        "yellow" => "yellow",
        "green" => "green",
        "graphite" => "slate",
        _ => "blue",
    }
}

fn gtk_css(accent: &str) -> String {
    let (r, g, b) = aqua_config::accent_rgb(accent);
    let hex = |k: f32| {
        format!(
            "#{:02x}{:02x}{:02x}",
            (r * k * 255.0).round().min(255.0) as u8,
            (g * k * 255.0).round().min(255.0) as u8,
            (b * k * 255.0).round().min(255.0) as u8
        )
    };
    GTK_CSS.replace("@define-color accent_bg_color #0a84ff;\n@define-color accent_color #0a7aff;", &format!(
        "@define-color accent_bg_color {};\n@define-color accent_color {};\n@define-color theme_selected_bg_color {};\n@define-color theme_selected_fg_color #ffffff;",
        hex(1.0), hex(0.95), hex(1.0)
    ))
}

fn write_appearance(dark: bool) {
    let Some(conf) = dirs_config() else { return };
    let accent = ACCENT.lock().unwrap().clone();
    let theme = aqua_notify::portal::gtk_theme_for(dark);
    let css4 = gtk_css(&accent);
    let css3 = css4
        .replace("windowcontrols { border-spacing: 8px; margin: 0 6px; }\n", "")
        .replace(" -gtk-icon-size: 8px;", "");
    for (v, css) in [("gtk-3.0", &css3), ("gtk-4.0", &css4)] {
        let ini = conf.join(v).join("settings.ini");
        let fresh = !ini.exists();
        let mut kv = vec![
            ("gtk-application-prefer-dark-theme", (dark as u8).to_string()),
            ("gtk-decoration-layout", "close,minimize,maximize:".to_string()),
            ("gtk-theme-name", theme.clone()),
        ];
        if fresh {
            kv.push(("gtk-font-name", "SF Pro Display 11".into()));
            kv.push(("gtk-enable-animations", "1".into()));
        }
        upsert_ini(&ini, &[("Settings", kv)]);
        write_if_ours(&conf.join(v).join("gtk.css"), css, MARK);
    }
    let q = |v: &str| format!("'{v}'");
    let kf = conf.join("glib-2.0/settings/keyfile");
    let fresh = !kf.exists();
    let mut ifc = vec![
        ("color-scheme", q(if dark { "prefer-dark" } else { "default" })),
        ("gtk-theme", q(&theme)),
        ("accent-color", q(gnome_accent(&accent))),
    ];
    if fresh {
        ifc.push(("font-name", q("SF Pro Display 11")));
        ifc.push(("document-font-name", q("SF Pro Display 11")));
        ifc.push(("enable-animations", "true".into()));
    }
    upsert_ini(
        &kf,
        &[
            ("org/gnome/desktop/wm/preferences", vec![("button-layout", q("close,minimize,maximize:"))]),
            ("org/gnome/desktop/interface", ifc),
        ],
    );
    write_dconf(dark, gnome_accent(&accent), theme);
    write_portal_prefs(&conf);
}

fn write_dconf(dark: bool, accent: &'static str, theme: String) {
    let has =
        std::env::var_os("PATH").map(|p| std::env::split_paths(&p).any(|d| d.join("dconf").is_file())).unwrap_or(false);
    if !has {
        return;
    }
    std::thread::spawn(move || {
        let kv = [
            ("/org/gnome/desktop/interface/color-scheme", if dark { "'prefer-dark'" } else { "'default'" }.to_string()),
            ("/org/gnome/desktop/interface/gtk-theme", format!("'{theme}'")),
            (
                "/org/gnome/desktop/interface/accent-color",
                match accent {
                    "purple" => "'purple'",
                    "pink" => "'pink'",
                    "red" => "'red'",
                    "orange" => "'orange'",
                    "yellow" => "'yellow'",
                    "green" => "'green'",
                    "slate" => "'slate'",
                    _ => "'blue'",
                }
                .to_string(),
            ),
        ];
        for (k, v) in kv {
            let _ = std::process::Command::new("dconf")
                .args(["write", k, v.as_str()])
                .env_remove("GSETTINGS_BACKEND")
                .stdout(std::process::Stdio::null())
                .stderr(std::process::Stdio::null())
                .status();
        }
    });
}

/// Route the portal's Settings (colour scheme, accent) to Aqua only: with `aqua;gtk`
/// xdg-desktop-portal merged in the GTK backend's (dconf) values.
fn write_portal_prefs(conf: &Path) {
    let kv: Vec<(&str, String)> = [
        ("default", "aqua;gtk;"),
        ("org.freedesktop.impl.portal.FileChooser", "aqua"),
        ("org.freedesktop.impl.portal.Screenshot", "aqua"),
        ("org.freedesktop.impl.portal.Settings", "aqua"),
        ("org.freedesktop.impl.portal.Inhibit", "aqua"),
        ("org.freedesktop.impl.portal.ScreenCast", "wlr"),
        ("org.freedesktop.impl.portal.RemoteDesktop", "wlr"),
        ("org.freedesktop.impl.portal.Secret", "gnome-keyring"),
    ]
    .iter()
    .map(|(k, v)| (*k, v.to_string()))
    .collect();
    let p = conf.join("xdg-desktop-portal/aqua-portals.conf");
    match std::fs::read_to_string(&p) {
        Ok(old) if !old.contains("generated by aqua") => {
            upsert_ini(&p, &[("preferred", vec![("org.freedesktop.impl.portal.Settings", "aqua".into())])])
        }
        _ => upsert_ini(&p, &[("preferred", kv)]),
    }
}

/// Live appearance switch from Control Center.
pub fn set_dark(dark: bool) {
    write_appearance(dark);
    let accent = ACCENT.lock().unwrap().clone();
    write_qt(dark, &accent);
}

/// KDE/Qt apps read their palette from `kdeglobals` (Breeze / Breeze Dark colours with the Aqua
/// accent as selection colour).
fn write_qt(dark: bool, accent: &str) {
    let Some(conf) = dirs_config() else { return };
    let (r, g, b) = aqua_config::accent_rgb(accent);
    let acc = format!("{},{},{}", (r * 255.0).round() as u8, (g * 255.0).round() as u8, (b * 255.0).round() as u8);
    let (win, view, text, btn) = if dark {
        ("42,42,44", "30,30,32", "235,235,240", "58,58,60")
    } else {
        ("236,236,238", "255,255,255", "29,29,31", "255,255,255")
    };
    let mut s = format!("# generated by aqua\n[General]\nColorScheme={}\nfont=SF Pro Display,10,-1,5,50,0,0,0,0,0\n\n[KDE]\nwidgetStyle=Fusion\n\n", if dark { "BreezeDark" } else { "BreezeLight" });
    for sec in ["View", "Window", "Button", "Selection", "Tooltip", "Complementary", "Header"] {
        let bg = match sec {
            "View" => view,
            "Button" => btn,
            "Selection" => acc.as_str(),
            _ => win,
        };
        let fg = if sec == "Selection" { "255,255,255" } else { text };
        s.push_str(&format!("[Colors:{sec}]\nBackgroundNormal={bg}\nBackgroundAlternate={bg}\nForegroundNormal={fg}\nDecorationFocus={acc}\nDecorationHover={acc}\n\n"));
    }
    let p = conf.join("kdeglobals");
    match std::fs::read_to_string(&p) {
        Ok(old) if !old.contains("generated by aqua") => {
            let mut secs: Vec<(&str, Vec<(&str, String)>)> =
                vec![("General", vec![("ColorScheme", if dark { "BreezeDark" } else { "BreezeLight" }.to_string())])];
            let names = ["View", "Window", "Button", "Selection", "Tooltip", "Complementary", "Header"];
            let heads: Vec<String> = names.iter().map(|n| format!("Colors:{n}")).collect();
            for (i, sec) in names.iter().enumerate() {
                let bg = match *sec {
                    "View" => view,
                    "Button" => btn,
                    "Selection" => acc.as_str(),
                    _ => win,
                };
                let fg = if *sec == "Selection" { "255,255,255" } else { text };
                secs.push((
                    heads[i].as_str(),
                    vec![
                        ("BackgroundNormal", bg.to_string()),
                        ("BackgroundAlternate", bg.to_string()),
                        ("ForegroundNormal", fg.to_string()),
                    ],
                ));
            }
            upsert_ini(&p, &secs);
        }
        _ => write_if_ours(&p, &s, "generated by aqua"),
    }
}
